# -*- coding: utf-8 -*-
"""sonidos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uglQMVveP6Ik8nYC4GOlg1r0OmcPCWW

# Instalar juego

Para instalar el juego, hacé click en el botón de play que está abajo de este texto.
"""

!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1KzxQMkSFcoK8GALl0xxs4rP1XJzXvejy' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1KzxQMkSFcoK8GALl0xxs4rP1XJzXvejy" -O sonidos.zip && rm -rf /tmp/cookies.txt
!unzip -o sonidos.zip

import IPython.display as ipd
from IPython.display import Audio
import random
from google.colab import output
import time
import os

def reproducir_sonido(archivo):
  return Audio(archivo, autoplay=True)

diccionario_sonidos={}             
archivos=os.listdir("/content")
for archivo in archivos:
  if archivo.endswith(".mp3"):
    diccionario_sonidos[archivo]=os.path.splitext(archivo)[0]

"""#Juego#
Escuchá el sonido, tratá de adivinar a qué corresponde, escribí abajo tu respuesta y dale al enter (tratá de escribir todo en minúscula y sin errores de ortografía).

Para empezar a jugar, hacé click en el boton de play.



Si querés saltear un sonido, escribí "next" en tu respuesta.
"""

#@title
sonidos = list(diccionario_sonidos.keys())
random.shuffle(sonidos)
for sonido in sonidos:
  a = reproducir_sonido(sonido)
  display(a)
 
  print("Tu respuesta:")
 
  continuar=True
  while continuar:
    respuesta=input()
    if respuesta==diccionario_sonidos[sonido]:
      print("¡Correcto!")
      continuar=False
    elif respuesta=="next":
      print("La respuesta era " + diccionario_sonidos[sonido]+".")
      continuar=False
    else:
      print("Volvé a intentarlo.")
  time.sleep(1)
  output.clear()